# hugo server --minify --themesDir ../.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://matthieupetiteau.github.io/'
title = 'Petiteau Matthieu'
theme = 'hugo-book'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'light'
  BookToC = true
  BookFavicon = 'favicon.png'
  BookSection = '/'
  BookDateFormat = 'January 2, 2006'
  BookSearch = false
  BookComments = false
  BookPortableLinks = false
  BookServiceWorker = false
  BookTranslatedOnly = false

[[menu.main]]
name = "Home"
url = "/index.html"
weight = 1



